# -*- coding: utf-8 -*-
"""financeForecasting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fzd2i7kahrvyl4wd1IADCGZsWY00YsMn
"""

import kagglehub

path = kagglehub.dataset_download("computingvictor/transactions-fraud-datasets")
print("Dataset downloaded to:", path)

from kagglehub import KaggleDatasetAdapter

df = kagglehub.dataset_load(
    KaggleDatasetAdapter.PANDAS,
    "computingvictor/transactions-fraud-datasets",
    "transactions_data.csv"
)

df.head()
print(df.columns)

import pandas as pd

# clean amount
df['amount'] = df['amount'].astype(str).str.replace('$', '', regex=False)
df['amount'] = pd.to_numeric(df['amount'], errors='coerce')

# Convert date column to datetime
df['date'] = pd.to_datetime(df['date'])

# Sort rows by date
df = df.sort_values('date')

# Compute monthly total expense
monthlyDf = df.groupby(pd.Grouper(key='date', freq='M'))['amount'].sum()
monthlyDf = monthlyDf.to_frame(name='monthly_expense')

# Filter date range
monthlyDf = monthlyDf[(monthlyDf.index.year >= 2010) & (monthlyDf.index.year <= 2018)]
print(monthlyDf)

!pip uninstall -y prophet fbprophet pystan
!pip install prophet

from prophet import Prophet



df = monthlyDf.reset_index()

df = df.rename(columns={
    "date": "ds",
    "monthly_expense": "y"
})

model = Prophet()
model.fit(df)

# Create future dates and predict
future = model.make_future_dataframe(periods=10, freq="M")
forecast = model.predict(future)

print(forecast[["ds", "yhat", "yhat_lower", "yhat_upper"]].tail(10))

from google.colab import drive
drive.mount('/content/drive')

import pickle

with open("/content/drive/MyDrive/prophet_model.pkl", "wb") as f:
    pickle.dump(model, f)

print("Model saved -> /content/drive/MyDrive/prophet_model.pkl")